// Component code training data based on your provided dataset
import { ComponentCodeTrainingData } from '../types';

export const COMPONENT_CODE_TRAINING_DATA: ComponentCodeTrainingData[] = [
  { componentName: "Acoustic Panel", objectPartCode: "ACPN", variations: ["Acoustic Panel"] },
  { componentName: "Actuator", objectPartCode: "BSAC", variations: ["Actuator"] },
  { componentName: "Actuator (HVAC)", objectPartCode: "EFAC", variations: ["Actuator (HVAC)", "HVAC Actuator"] },
  { componentName: "Actuator (Pneumatic)", objectPartCode: "PNAC", variations: ["Actuator (Pneumatic)", "Pneumatic Actuator"] },
  { componentName: "Actuator Link", objectPartCode: "ACLK", variations: ["Actuator Link"] },
  { componentName: "Adjusting Collar", objectPartCode: "ADCL", variations: ["Adjusting Collar"] },
  { componentName: "Adjusting Mechanism", objectPartCode: "DPAJ", variations: ["Adjusting Mechanism"] },
  { componentName: "Adjusting Nut", objectPartCode: "AJNT", variations: ["Adjusting Nut"] },
  { componentName: "AED", objectPartCode: "AED0", variations: ["AED"] },
  { componentName: "Air and Grease Swivel", objectPartCode: "AGSW", variations: ["Air and Grease Swivel"] },
  { componentName: "Air Terminal", objectPartCode: "LPAT", variations: ["Air Terminal"] },
  { componentName: "Air Valve", objectPartCode: "AVAL", variations: ["Air Valve"] },
  { componentName: "Airconditioner Coil", objectPartCode: "ACCL", variations: ["Airconditioner Coil", "AC Coil", "Air Conditioner Coil"] },
  { componentName: "Alumina Tile", objectPartCode: "ALTL", variations: ["Alumina Tile"] },
  { componentName: "Anchor Point", objectPartCode: "ANPT", variations: ["Anchor Point"] },
  { componentName: "Antenna", objectPartCode: "ANTE", variations: ["Antenna"] },
  { componentName: "Appliance", objectPartCode: "APNC", variations: ["Appliance"] },
  { componentName: "Arc Chute", objectPartCode: "ARCH", variations: ["Arc Chute"] },
  { componentName: "Arm", objectPartCode: "ARM0", variations: ["Arm", "Link Arm", "Torque Arm", "Connecting Arm"] },
  { componentName: "Auxiliary Switch", objectPartCode: "AXSW", variations: ["Auxiliary Switch", "Aux Switch"] },
  { componentName: "Ball (Internal)", objectPartCode: "BALI", variations: ["Ball (Internal)", "Internal Ball"] },
  { componentName: "Ball Joint", objectPartCode: "BLJT", variations: ["Ball Joint"] },
  { componentName: "Ball Valve", objectPartCode: "BLVL", variations: ["Ball Valve"] },
  { componentName: "Ball Valve (Electric)", objectPartCode: "BVLE", variations: ["Ball Valve (Electric)", "Electric Ball Valve"] },
  { componentName: "Bar", objectPartCode: "BAR0", variations: ["Bar"] },
  { componentName: "Barrel", objectPartCode: "BRRL", variations: ["Barrel"] },
  { componentName: "Barrier Sheet/Membrane", objectPartCode: "BSMR", variations: ["Barrier Sheet/Membrane", "Barrier Sheet", "Barrier Membrane"] },
  { componentName: "Base Plate", objectPartCode: "BSPL", variations: ["Base Plate"] },
  { componentName: "Battery (Lead Acid)", objectPartCode: "BTLA", variations: ["Battery (Lead Acid)", "Lead Acid Battery"] },
  { componentName: "Battery (Lead Cadmium)", objectPartCode: "LCBA", variations: ["Battery (Lead Cadmium)", "Lead Cadmium Battery"] },
  { componentName: "Battery (Lithium)", objectPartCode: "EIBL", variations: ["Battery (Lithium)", "Lithium Battery"] },
  { componentName: "Battery (UPS)", objectPartCode: "BTUP", variations: ["Battery (UPS)", "UPS Battery"] },
  { componentName: "Battery (VRLA)", objectPartCode: "BTVR", variations: ["Battery (VRLA)", "VRLA Battery"] },
  { componentName: "Beam", objectPartCode: "BEAM", variations: ["Beam"] },
  { componentName: "Bearing", objectPartCode: "BRNG", variations: ["Bearing"] },
  { componentName: "Bearing (Babbitt)", objectPartCode: "BRBT", variations: ["Bearing (Babbitt)", "Babbitt Bearing"] },
  { componentName: "Bearing Housing", objectPartCode: "BRHS", variations: ["Bearing Housing"] },
  { componentName: "Bell Housing", objectPartCode: "BLHS", variations: ["Bell Housing"] },
  { componentName: "Bellow", objectPartCode: "BLLW", variations: ["Bellow", "Bellows"] },
  { componentName: "Bladder", objectPartCode: "BLDR", variations: ["Bladder"] },
  { componentName: "Blade", objectPartCode: "BLDE", variations: ["Blade"] },
  { componentName: "Blade (Valve)", objectPartCode: "BLDV", variations: ["Blade (Valve)", "Valve Blade"] },
  { componentName: "Blanket Insulation", objectPartCode: "BLIN", variations: ["Blanket Insulation"] },
  { componentName: "Bleed Valve", objectPartCode: "CBVL", variations: ["Bleed Valve"] },
  { componentName: "Blower Wheel", objectPartCode: "BLWH", variations: ["Blower Wheel"] },
  { componentName: "Body", objectPartCode: "BODY", variations: ["Body"] },
  { componentName: "Bogie Wheel", objectPartCode: "BGWH", variations: ["Bogie Wheel"] },
  { componentName: "Bogie Wheel Axle", objectPartCode: "BGWA", variations: ["Bogie Wheel Axle"] },
  { componentName: "Boot", objectPartCode: "BOOT", variations: ["Boot"] },
  { componentName: "Bottom Cover", objectPartCode: "BTCV", variations: ["Bottom Cover"] },
  { componentName: "Bracing", objectPartCode: "SSBG", variations: ["Bracing"] },
  { componentName: "Brake Disc", objectPartCode: "CLDK", variations: ["Brake Disc"] },
  { componentName: "Brake Pad", objectPartCode: "CLPD", variations: ["Brake Pad"] },
  { componentName: "Brake Release Valve", objectPartCode: "BRRV", variations: ["Brake Release Valve"] },
  { componentName: "Breather", objectPartCode: "BRTH", variations: ["Breather"] },
  { componentName: "Buffer Dust Cover", objectPartCode: "BRDC", variations: ["Buffer Dust Cover"] },
  { componentName: "Bumper", objectPartCode: "BMPR", variations: ["Bumper"] },
  { componentName: "Bund (Steel)", objectPartCode: "BUND", variations: ["Bund (Steel)", "Steel Bund"] },
  { componentName: "Busbar", objectPartCode: "BSBR", variations: ["Busbar", "Bus Bar"] },
  { componentName: "Bushing (Electrical)", objectPartCode: "BSEL", variations: ["Bushing (Electrical)", "Electrical Bushing"] },
  { componentName: "Bushing (Steel)", objectPartCode: "STBS", variations: ["Bushing (Steel)", "Steel Bushing", "Bushing-Steel"] },
  { componentName: "Button", objectPartCode: "BTNN", variations: ["Button"] },
  { componentName: "Cable", objectPartCode: "CABL", variations: ["Cable"] },
  { componentName: "Cable Conduit", objectPartCode: "CBCN", variations: ["Cable Conduit"] },
  { componentName: "Cable Gland", objectPartCode: "CBGL", variations: ["Cable Gland"] },
  { componentName: "Cable Tray", objectPartCode: "CBTR", variations: ["Cable Tray"] },
  { componentName: "Cage", objectPartCode: "CAGE", variations: ["Cage"] },
  { componentName: "Calibration Column", objectPartCode: "CACL", variations: ["Calibration Column"] },
  { componentName: "Camera", objectPartCode: "CMRA", variations: ["Camera"] },
  { componentName: "Canopy", objectPartCode: "CNPY", variations: ["Canopy"] },
  { componentName: "Capacitor", objectPartCode: "CAPC", variations: ["Capacitor"] },
  { componentName: "Carbon Brush", objectPartCode: "HRSH", variations: ["Carbon Brush"] },
  { componentName: "Carrier Ring", objectPartCode: "CARR", variations: ["Carrier Ring"] },
  { componentName: "Carry Roller", objectPartCode: "CARL", variations: ["Carry Roller"] },
  { componentName: "Casing", objectPartCode: "CSNG", variations: ["Casing"] },
  { componentName: "Ceiling Panel", objectPartCode: "CPNL", variations: ["Ceiling Panel"] },
  { componentName: "Ceramic Liner", objectPartCode: "CRLR", variations: ["Ceramic Liner"] },
  { componentName: "Chain", objectPartCode: "CHAN", variations: ["Chain"] },
  { componentName: "Chain (Engine Timing)", objectPartCode: "CHET", variations: ["Chain (Engine Timing)", "Engine Timing Chain"] },
  { componentName: "Chain Link", objectPartCode: "CHLK", variations: ["Chain Link"] },
  { componentName: "Check Valve", objectPartCode: "CKVL", variations: ["Check Valve"] },
  { componentName: "Circuit Breaker (Panel)", objectPartCode: "CTBR", variations: ["Circuit Breaker (Panel)", "Panel Circuit Breaker"] },
  { componentName: "Clamp", objectPartCode: "CLMP", variations: ["Clamp"] },
  { componentName: "Clamp Plate", objectPartCode: "CMPL", variations: ["Clamp Plate"] },
  { componentName: "Clog Indicator", objectPartCode: "CLIN", variations: ["Clog Indicator"] },
  { componentName: "Comb", objectPartCode: "COMB", variations: ["Comb"] },
  { componentName: "Commutator", objectPartCode: "CMTR", variations: ["Commutator"] },
  { componentName: "Compensation Spring", objectPartCode: "SPRG", variations: ["Compensation Spring"] },
  { componentName: "Concrete Post", objectPartCode: "CPST", variations: ["Concrete Post"] },
  { componentName: "Concrete Wall", objectPartCode: "CNWL", variations: ["Concrete Wall"] },
  { componentName: "Conductive Ring", objectPartCode: "CDRG", variations: ["Conductive Ring"] },
  { componentName: "Connection Flange", objectPartCode: "CFNG", variations: ["Connection Flange"] },
  { componentName: "Connection Plug", objectPartCode: "CNPL", variations: ["Connection Plug"] },
  { componentName: "Constant Level Oiler", objectPartCode: "CLOI", variations: ["Constant Level Oiler"] },
  { componentName: "Contact Probe", objectPartCode: "CTPB", variations: ["Contact Probe"] },
  { componentName: "Contactor", objectPartCode: "CONT", variations: ["Contactor"] },
  { componentName: "Cooling Fin", objectPartCode: "CLFN", variations: ["Cooling Fin"] },
  { componentName: "Cooling Plate", objectPartCode: "CPLT", variations: ["Cooling Plate"] },
  { componentName: "Core Bolt", objectPartCode: "CRBT", variations: ["Core Bolt"] },
  { componentName: "Core Plug", objectPartCode: "CRPG", variations: ["Core Plug"] },
  { componentName: "Core Winding", objectPartCode: "TXCW", variations: ["Core Winding"] },
  { componentName: "Corrugated Sheet", objectPartCode: "CSHT", variations: ["Corrugated Sheet"] },
  { componentName: "Counter Meter", objectPartCode: "CTME", variations: ["Counter Meter"] },
  { componentName: "Counterweight", objectPartCode: "CWGT", variations: ["Counterweight", "Counter Weight"] },
  { componentName: "Counterweight (Lower - Eccentric)", objectPartCode: "LECW", variations: ["Counterweight (Lower - Eccentric)", "Lower Eccentric Counterweight"] },
  { componentName: "Counterweight (Upper - Eccentric)", objectPartCode: "UECW", variations: ["Counterweight (Upper - Eccentric)", "Upper Eccentric Counterweight"] },
  { componentName: "Coupler", objectPartCode: "CPLR", variations: ["Coupler"] },
  { componentName: "Coupler Module", objectPartCode: "CPMD", variations: ["Coupler Module"] },
  { componentName: "Coupling", objectPartCode: "CPLG", variations: ["Coupling"] },
  { componentName: "Coupling (Magnetic)", objectPartCode: "CPMG", variations: ["Coupling (Magnetic)", "Magnetic Coupling"] },
  { componentName: "Coupling Adaptor", objectPartCode: "CLDP", variations: ["Coupling Adaptor", "Coupling Adapter"] },
  { componentName: "Cover Plate", objectPartCode: "CVPL", variations: ["Cover Plate"] },
  { componentName: "CPU", objectPartCode: "CPU0", variations: ["CPU"] },
  { componentName: "Cross Beam", objectPartCode: "CRBM", variations: ["Cross Beam"] },
  { componentName: "Curtain/Blind", objectPartCode: "CTBD", variations: ["Curtain/Blind", "Curtain", "Blind"] },
  { componentName: "Cushion", objectPartCode: "BCCH", variations: ["Cushion"] },
  { componentName: "Delineator", objectPartCode: "DLTR", variations: ["Delineator"] },
  { componentName: "Density Transmitter", objectPartCode: "DYTR", variations: ["Density Transmitter"] },
  { componentName: "Detector", objectPartCode: "DETC", variations: ["Detector"] },
  { componentName: "Detector Line", objectPartCode: "RSDL", variations: ["Detector Line"] },
  { componentName: "Diaphragm Valve", objectPartCode: "DPVL", variations: ["Diaphragm Valve"] },
  { componentName: "Diesel Filter", objectPartCode: "DSFL", variations: ["Diesel Filter"] },
  { componentName: "Diffuser", objectPartCode: "DFSR", variations: ["Diffuser"] },
  { componentName: "Fan", objectPartCode: "FAN0", variations: ["Fan", "Cooling Fan", "Exhaust Fan"] },
  // Additional common components to reduce AI calls
  { componentName: "Motor", objectPartCode: "MOTR", variations: ["Motor", "Electric Motor", "Drive Motor"] },
  { componentName: "Pump", objectPartCode: "PUMP", variations: ["Pump", "Water Pump", "Oil Pump"] },
  { componentName: "Valve", objectPartCode: "VALV", variations: ["Valve", "Control Valve", "Safety Valve"] },
  { componentName: "Filter", objectPartCode: "FLTR", variations: ["Filter", "Air Filter", "Oil Filter"] },
  { componentName: "Sensor", objectPartCode: "SNSR", variations: ["Sensor", "Temperature Sensor", "Pressure Sensor"] },
  { componentName: "Switch", objectPartCode: "SWTC", variations: ["Switch", "Limit Switch", "Pressure Switch"] },
  { componentName: "Relay", objectPartCode: "RELY", variations: ["Relay", "Control Relay", "Safety Relay"] },
  { componentName: "Transformer", objectPartCode: "TRFM", variations: ["Transformer", "Power Transformer", "Control Transformer"] },
  { componentName: "Heater", objectPartCode: "HTER", variations: ["Heater", "Electric Heater", "Immersion Heater"] },
  { componentName: "Cooler", objectPartCode: "COLR", variations: ["Cooler", "Oil Cooler", "Air Cooler"] },
  { componentName: "Gasket", objectPartCode: "GSKT", variations: ["Gasket", "Seal Gasket", "Flange Gasket"] },
  { componentName: "Seal", objectPartCode: "SEAL", variations: ["Seal", "Oil Seal", "Mechanical Seal"] },
  { componentName: "Spring", objectPartCode: "SPRG", variations: ["Spring", "Compression Spring", "Return Spring"] },
  { componentName: "Bolt", objectPartCode: "BOLT", variations: ["Bolt", "Hex Bolt", "Anchor Bolt"] },
  { componentName: "Nut", objectPartCode: "NUT0", variations: ["Nut", "Hex Nut", "Lock Nut"] },
  { componentName: "Washer", objectPartCode: "WSHR", variations: ["Washer", "Flat Washer", "Spring Washer"] },
  { componentName: "Screw", objectPartCode: "SCRW", variations: ["Screw", "Cap Screw", "Set Screw"] },
  { componentName: "Pin", objectPartCode: "PIN0", variations: ["Pin", "Dowel Pin", "Cotter Pin"] },
  { componentName: "Shaft", objectPartCode: "SHFT", variations: ["Shaft", "Drive Shaft", "Input Shaft"] },
  { componentName: "Gear", objectPartCode: "GEAR", variations: ["Gear", "Spur Gear", "Worm Gear"] },
  { componentName: "Belt", objectPartCode: "BELT", variations: ["Belt", "V-Belt", "Timing Belt"] },
  { componentName: "Pulley", objectPartCode: "PLLY", variations: ["Pulley", "Drive Pulley", "Idler Pulley"] },
  { componentName: "Roller", objectPartCode: "RLLR", variations: ["Roller", "Guide Roller", "Support Roller"] },
  { componentName: "Wheel", objectPartCode: "WHEL", variations: ["Wheel", "Drive Wheel", "Guide Wheel"] },
  { componentName: "Disc", objectPartCode: "DISC", variations: ["Disc", "Brake Disc", "Clutch Disc"] },
  { componentName: "Plate", objectPartCode: "PLTE", variations: ["Plate", "Base Plate", "Cover Plate"] },
  { componentName: "Panel", objectPartCode: "PANL", variations: ["Panel", "Control Panel", "Access Panel"] },
  { componentName: "Cover", objectPartCode: "COVR", variations: ["Cover", "Protective Cover", "End Cover"] },
  { componentName: "Housing", objectPartCode: "HSNG", variations: ["Housing", "Motor Housing", "Pump Housing"] },
  { componentName: "Frame", objectPartCode: "FRAM", variations: ["Frame", "Motor Frame", "Support Frame"] },
  { componentName: "Bracket", objectPartCode: "BRKT", variations: ["Bracket", "Mounting Bracket", "Support Bracket"] },
  { componentName: "Connector", objectPartCode: "CONN", variations: ["Connector", "Electrical Connector", "Pipe Connector"] },
  { componentName: "Adapter", objectPartCode: "ADPT", variations: ["Adapter", "Coupling Adapter", "Pipe Adapter"] },
  { componentName: "Fitting", objectPartCode: "FTTG", variations: ["Fitting", "Pipe Fitting", "Hydraulic Fitting"] },
  { componentName: "Hose", objectPartCode: "HOSE", variations: ["Hose", "Hydraulic Hose", "Air Hose"] },
  { componentName: "Pipe", objectPartCode: "PIPE", variations: ["Pipe", "Steel Pipe", "Drain Pipe"] },
  { componentName: "Tube", objectPartCode: "TUBE", variations: ["Tube", "Steel Tube", "Copper Tube"] },
  { componentName: "Wire", objectPartCode: "WIRE", variations: ["Wire", "Control Wire", "Power Wire"] },
  { componentName: "Fuse", objectPartCode: "FUSE", variations: ["Fuse", "Cartridge Fuse", "Blade Fuse"] },
  { componentName: "Breaker", objectPartCode: "BRKR", variations: ["Breaker", "Circuit Breaker", "Main Breaker"] },
  { componentName: "Starter", objectPartCode: "STRT", variations: ["Starter", "Motor Starter", "DOL Starter"] },
  { componentName: "Drive", objectPartCode: "DRIV", variations: ["Drive", "Variable Drive", "Frequency Drive"] },
  { componentName: "Controller", objectPartCode: "CTRL", variations: ["Controller", "Motor Controller", "Process Controller"] },
  { componentName: "Display", objectPartCode: "DSPL", variations: ["Display", "LCD Display", "LED Display"] },
  { componentName: "Indicator", objectPartCode: "INDC", variations: ["Indicator", "Status Indicator", "Level Indicator"] },
  { componentName: "Alarm", objectPartCode: "ALRM", variations: ["Alarm", "Audio Alarm", "Visual Alarm"] },
  { componentName: "Light", objectPartCode: "LGHT", variations: ["Light", "Indicator Light", "Warning Light"] },
  { componentName: "Lamp", objectPartCode: "LAMP", variations: ["Lamp", "Signal Lamp", "Pilot Lamp"] },
  { componentName: "Bulb", objectPartCode: "BULB", variations: ["Bulb", "Incandescent Bulb", "LED Bulb"] }
];